### ISSUE TITLE
Failed to Compile, with this error.

### ISSUE THREAD

**Issue by ns-bc** [fb55/htmlparser2#1237]
What could be the cause of this? In a CRA.

```
./node_modules/htmlparser2/lib/esm/index.js 67:9
Module parse failed: Unexpected token (67:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   return getFeed(parseDOM(feed, options));
| }
> export * as DomUtils from "domutils"; // Old name for DomHandler      
|
| export { DomHandler as DefaultHandler };
```

**Comment by yanm1ng** [comment]
same problem

**Comment by yarrrrrrik** [comment]
+1

**Comment by yannickrocks** [comment]
+1

**Comment by Diljeetsinghsuri** [comment]
Was facing the same issue. It seems to be the issue with the latest version. A quick workaround is to fix the version of htmlparser2 in your package json and re-run npm install cmd. So It won't update the package version to latest.

**Comment by lukescott** [comment]
`export * as ns` is a later extension of the module syntax and is supported in webpack 5. 

See https://github.com/webpack/webpack/issues/10460

I ran into this because:

- Our projects are still using webpack 4
- We are using `html-to-react`, which updated from htmlparser2 7 to 8 between 1.4 and 1.5 and we are using `^`.

A few solutions:

- Upgrade to webpack 5
- If you are using babel already, you can use `@babel/plugin-proposal-export-namespace-from` as mentioned in the webpack issue
- You can target files/packages that use htmlparser2 and use `resolve.mainFields` in a rule to tell it to use `main` instead of `module`. For us doing this globally broke other things.
- Lock the dependency to a version that still uses htmlparser2 v7.

**Comment by ljharb** [comment]
Isn’t the easy fix to do it in two lines?
